// <auto-generated />
using System;
using InternManagementSystem.DataRepository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InternManagenmentSystem.Migrations
{
    [DbContext(typeof(InternDbContext))]
    [Migration("20220831072757_firstmigation")]
    partial class firstmigation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InternManagementSystem.Models.InternDesignation", b =>
                {
                    b.Property<int>("SNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepartMent")
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("DesignationId")
                        .HasColumnType("int");

                    b.Property<string>("DesignationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("SNo");

                    b.ToTable("InternDesignation");
                });

            modelBuilder.Entity("InternManagementSystem.Models.InternLeaveRequest", b =>
                {
                    b.Property<int>("SNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InternId")
                        .HasColumnType("int");

                    b.Property<string>("InternName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeaveDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeaveReason")
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LeaveType")
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("SNo");

                    b.ToTable("InternLeaveRequest");
                });

            modelBuilder.Entity("InternManagementSystem.Models.InternRecord", b =>
                {
                    b.Property<int>("InternId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DesigntionId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InternDesignationSNo")
                        .HasColumnType("int");

                    b.Property<string>("InternName")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("InternId");

                    b.HasIndex("InternDesignationSNo");

                    b.ToTable("InternRecord");
                });

            modelBuilder.Entity("InternManagementSystem.Models.InternWorkingHour", b =>
                {
                    b.Property<int>("SNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyMonthlyWorkingHours")
                        .HasColumnType("int");

                    b.Property<int>("InternId")
                        .HasColumnType("int");

                    b.Property<int>("InternMonthlyWorkingHours")
                        .HasColumnType("int");

                    b.HasKey("SNo");

                    b.ToTable("InternWorkingHour");
                });

            modelBuilder.Entity("InternManagementSystem.Models.Login", b =>
                {
                    b.Property<int>("SNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SNo");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("InternManagementSystem.Models.Register", b =>
                {
                    b.Property<int>("SNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConfirmPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SNo");

                    b.ToTable("Registers");
                });

            modelBuilder.Entity("InternManagementSystem.Models.InternRecord", b =>
                {
                    b.HasOne("InternManagementSystem.Models.InternDesignation", "InternDesignation")
                        .WithMany()
                        .HasForeignKey("InternDesignationSNo");
                });
#pragma warning restore 612, 618
        }
    }
}
